[package]
name = "githerder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easy-parallel = "3.2"
git2 = "0.17"
