[package]
name = "githerder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-executor = "1.5"
async-process = "1.6"
futures = "0.3"
git2 = "0.17"
